### ISSUE TITLE
can't start Kitematic 0.7.6

### ISSUE THREAD

**Issue by sputnik62** [kitematic/kitematic#839]
I get Starting Docker VM to go to 99% and then:
ENOENT: no such file or directory, open '/Volumes/HDD/Users/<redacted>/.docker/machine/machines/dev/ca.pem'

**Comment by DRuffer** [comment]
I also get a similar error on Win8.1. I found https://kitematic.com/docs/known-issues/, but I have no clue how to execute docker-machine.


DaR






From: Leon Katsnelson
Sent: ‎Monday‎, ‎July‎ ‎20‎, ‎2015 ‎9‎:‎49‎ ‎AM
To: kitematic/kitematic





I get Kitematic to go to 99% and then:
ENOENT: no such file or directory, open '/Volumes/HDD/Users//.docker/machine/machines/dev/ca.pem'

**Comment by FrenchBen** [comment]
@sputnik62 It looks like you have a custom setup for your current user? Is your home directory mounted to an external drive?
Can you list the content of the .docker folder?
`ls ~/.docker/machine/machines/dev/`

**Comment by FrenchBen** [comment]
@DRuffer If you'd like you can also open VirtualBox and remove the Kitematic created VM.

**Comment by DRuffer** [comment]
I've removed the Kitematic VM (deleting all files) multiple times already.  DaR






From: FrenchBen
Sent: ‎Monday‎, ‎July‎ ‎20‎, ‎2015 ‎11‎:‎51‎ ‎AM
To: kitematic/kitematic
Cc: Dennis Ruffer





@DRuffer If you'd like you can also open VirtualBox and remove the Kitematic created VM.

**Comment by DRuffer** [comment]
The latest error after removing the Kitematic VM once again:


C:\Users\<redacted>\disk.vmdk”… Creating dynamic image with size 20971520000 bytes (2000MB)… Error creating machine:

Maximum number of retries (60) exceeded…


Why can't I cut and paste that message to this email?


DaR






From: Dennis Ruffer
Sent: ‎Monday‎, ‎July‎ ‎20‎, ‎2015 ‎12‎:‎05‎ ‎PM
To: kitematic/kitematic, kitematic/kitematic





I've removed the Kitematic VM (deleting all files) multiple times already.  DaR






From: FrenchBen
Sent: ‎Monday‎, ‎July‎ ‎20‎, ‎2015 ‎11‎:‎51‎ ‎AM
To: kitematic/kitematic
Cc: Dennis Ruffer





@DRuffer If you'd like you can also open VirtualBox and remove the Kitematic created VM.

**Comment by jeffdm** [comment]
@sputnik62 seems like KM didn't pick up your home directory correctly. What's the output of `echo $HOME` in a terminal?

Thanks for the issue

**Comment by mchiang0610** [comment]
@sputnik62 @DRuffer 

Can you try opening a command prompt (terminal), and try regenerating the certificates? 

```
docker-machine regenerate-certs -f dev 
```

**Comment by DRuffer** [comment]
C:\Users\Dennis\AppData\Local\Kitematic\app-0.7.6\resources\resources>docker-machine regenerate-certs -f dev
Regenerating TLS certificates
Error: Host does not exist: dev



DaR





From: Michael Chiang
Sent: ‎Tuesday‎, ‎July‎ ‎21‎, ‎2015 ‎4‎:‎29‎ ‎PM
To: kitematic/kitematic
Cc: Dennis Ruffer





@sputnik62 @DRuffer 

Can you try opening a command prompt (terminal), and try regenerating the certificates? 
docker-machine regenerate-certs -f dev

**Comment by sputnik62** [comment]
[~]$ docker-machine regenerate-certs -f dev
Regenerating TLS certificates
Error getting SSH command: exit status 255

**Comment by DRuffer** [comment]
I also got that, once I used the right name:


C:\Users\Dennis\AppData\Local\Kitematic\app-0.7.6\resources\resources>docker-machine regenerate-certs -f kitematic
Regenerating TLS certificates
Error getting SSH command: exit status 255


That hung when the kinematic vm was running and when trying to create the Dev vm:


C:\Users\Dennis\AppData\Local\Kitematic\app-0.7.6\resources\resources>docker-machine create -d virtualbox dev
Creating VirtualBox VM...
Creating SSH key...
Starting VirtualBox VM...
Starting VM...



DaR





From: Leon Katsnelson
Sent: ‎Tuesday‎, ‎July‎ ‎21‎, ‎2015 ‎6‎:‎44‎ ‎PM
To: kitematic/kitematic
Cc: Dennis Ruffer





[~]$ docker-machine regenerate-certs -f dev
Regenerating TLS certificates
Error getting SSH command: exit status 255

**Comment by rwatts3** [comment]
Any luck on resolving this issue ? 
I received the same issue on Windows 7 . Hangs at 99% .

**Comment by DRuffer** [comment]
Not yet.  Discussion is over here: https://github.com/kitematic/kitematic/issues/386#issuecomment-123804467

**Comment by mchiang0610** [comment]
Still have the issue on 0.8?

**Comment by ezeql** [comment]
another win 8.1 user with the same problem

**Comment by mchiang0610** [comment]
@ezeql Are installing through Docker Toolbox? Many bugs have been fixed since 0.7.6.

https://www.docker.com/toolbox

**Comment by ezeql** [comment]
@mchiang0610 Yep, I did

**Comment by Rocklviv** [comment]
Kinematic version: **0.8.2**
Still same issue:
* **ENOENT: no such file or directory, open 'C:\Users\<redacted>\ca.pem'** 

**Windows: 8.1 / 10**

**Comment by mchiang0610** [comment]
Merging with #1029

**Comment by thomasshanks** [comment]
Still having the issue.  Why was it merged with unrelated bug #1029?

**Comment by nicodmf** [comment]
I resolv this with cygwin uninstall

**Comment by mchiang0610** [comment]
@thomasshanks Sorry about that. There is a mix of issues in this thread - they almost all point to one single problem - machine VM wasn't provisioned correctly.

**Comment by jcampon** [comment]
Hi,

I think the problem is that in some parts the VM is referred as "dev" whereas in some other parts (like the real physical path where the VM files are stored, etc) is referred as "default"

What I've done is just regenerate the certificates using the proper VM name and it now works!

Run from the Windows command line:

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Program Files\Docker Toolbox>docker-machine regenerate-certs -f dev
Regenerating TLS certificates
Error: Host does not exist: dev

C:\Program Files\Docker Toolbox>docker-machine regenerate-certs -f default
Regenerating TLS certificates

C:\Program Files\Docker Toolbox>
```
And that will do the trick!

**Comment by Rocklviv** [comment]
```
PS C:\Program Files\Docker Toolbox> .\docker-machine.exe regenerate-certs -f default                                    Regenerating TLS certificates
OS type not recognized
```
Windows 10. 
So there are some problems with Windows 10.

**Comment by jcampon** [comment]
Could be... I ran this on Windows 7 only. 
Also, it's probably nothing but have you tried running the commands from the good old command line (cmd) - mayve with admin priviledges - instead of from PowerShell? Don't think it'll make any difference but just in case..

**Comment by Rocklviv** [comment]
Yes, i run it in PS and old good cmd :) but still no result. 
Same issue as with admin privileges.

**Comment by FrenchBen** [comment]
@Rocklviv if you're getting 'OS type not recognized' from docker-machine it means that the VM wasn't properly created
Can you provide us with the output of:
`docker-machine ls`

**Comment by serhiypal** [comment]
I had the same issue with kitematic running on Windows 7, after listings docker machines I found I have the only default, so I regenerated certs as mentioned above for default not for dev and it resolved my issue

**Comment by FrenchBen** [comment]
@serhiypal thanks for sharing - Glad this solution also worked for you.

**Comment by Rocklviv** [comment]
@FrenchBen Thanks. I had recreate VM and regenerate certs issue was resolved.
